language: android

jdk:
 - oraclejdk8

env:
    global:
        - ANDROID_TARGET=android-28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3
        - ANDROID_ABI=armeabi-v7a

before_install:
    - yes | sdkmanager "platforms;android-29"
    - yes | sdkmanager "platforms;android-24"

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-22
  licenses:
    - .+

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
    - ./gradlew assembleDebug
    - ./gradlew connectedDebugAndroidTest

notifications:
  email: false
